# Generated by Django 5.2.8 on 2025-12-02 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_about_email_about_field_about_full_name_about_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='profession',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
