# Generated by Django 5.2.8 on 2025-12-03 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_project_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workexperience',
            name='responsibilities',
        ),
        migrations.AddField(
            model_name='workexperience',
            name='responsibility_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='responsibility_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='responsibility_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='responsibility_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='responsibility_5',
            field=models.TextField(blank=True, null=True),
        ),
    ]
