# Generated by Django 5.2.8 on 2025-12-03 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_workexperience_responsibilities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='challenge_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='challenge_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='reason_for_the_project',
            field=models.TextField(blank=True, null=True),
        ),
    ]
