# Generated by Django 5.2.8 on 2025-12-04 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_certification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certification',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='certification',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='certificates/'),
        ),
    ]
