# Generated by Django 5.2.8 on 2025-12-05 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_certification_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referee',
            name='email',
        ),
        migrations.AddField(
            model_name='referee',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='referee',
            name='company',
            field=models.CharField(),
        ),
    ]
