# Generated by Django 5.2.8 on 2025-12-05 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_referee_email_referee_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workexperience',
            name='responsibility_6',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='responsibility_7',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='responsibility_8',
            field=models.TextField(blank=True, null=True),
        ),
    ]
