# Generated by Django 5.2.8 on 2025-12-05 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_workexperience_responsibility_6_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='nationality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
