# Generated by Django 5.2.8 on 2025-12-11 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_project_challenges_project_problem_solved_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='challenges',
        ),
        migrations.RemoveField(
            model_name='project',
            name='reason',
        ),
    ]
