# Generated by Django 5.2.8 on 2025-12-12 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_project_video_url_project_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='challenge_1',
        ),
        migrations.RemoveField(
            model_name='project',
            name='challenge_2',
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('mobile', 'Mobile App-Project'), ('web', 'Website=Project'), ('hardware', 'Hardware-Project'), ('software', 'Software-Project')], max_length=20),
        ),
    ]
