# Generated by Django 5.2.8 on 2025-12-12 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_remove_project_challenge_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='icon',
            field=models.CharField(blank=True, help_text='FontAwesome class, e.g. fa-brands fa-python', max_length=100, null=True),
        ),
    ]
