# Generated by Django 5.2.8 on 2025-12-15 13:25

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_skill_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='cv')),
            ],
        ),
        migrations.AlterField(
            model_name='about',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='profile image'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='certificate image'),
        ),
        migrations.AlterField(
            model_name='project',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='project image'),
        ),
        migrations.AlterField(
            model_name='project',
            name='video',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='project video'),
        ),
    ]
