# Generated by Django 5.2.8 on 2025-12-16 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_cv_alter_about_photo_alter_certification_photo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cv',
            old_name='cv',
            new_name='cv_file',
        ),
    ]
